In [33]:
# Vector Operation
# Multiply with scale or adding two vector
# Multiplication of two vectors using inner product or dot product


In [34]:
import numpy as np

In [35]:
# Multiplication with vector

In [36]:
u = np.array([1, 2, 3 ,4])
u*2

array([2, 4, 6, 8])

In [37]:
# Adding two vectors

In [38]:
v = np.array([5, 6, 7, 8])

In [39]:
u+v

array([ 6,  8, 10, 12])

In [40]:
# Multiplication of two vector
u = np.array([1,2, 3, 4])
v = np.array([5, 6, 7,8])
u*v

array([ 5, 12, 21, 32])

In [106]:
def vector_vector_multipication(u,v):
    assert u.shape[0] == v.shape[0]               # Making sure size of each vector is equal
    result = 0.0
    number_of_element = u.shape[0]     

    for i in range (number_of_element):               # Calculating result
        
       
        result = result +  (u[i] * v[i])
       
    print(result)
    return result                                   # returing result

In [107]:
u = np.array([1,2, 3, 4])
v = np.array([5, 6, 7,8])
vector_vector_multipication(u,v)


70.0


np.float64(70.0)

In [108]:
5, 12 , 21, 32

(5, 12, 21, 32)

In [109]:
def matrix_vector_multipication(U, v):
    
    assert U.shape[1] == v.shape[0]
    resultant_number_of_rows  = U.shape[0]
    result = np.zeros(resultant_number_of_rows)

    for i in range( resultant_number_of_rows):
        result [i] = vector_vector_multipication(U[i],v)

    return result
        
    

In [110]:
U = np.array([[2, 4, 5, 6],[1, 2 , 1, 2], [3, 1 , 2 , 1]])
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [111]:
U.shape # 3 rows and 4 columns

(3, 4)

In [112]:
d = np.array([1, 0, 0, 2])

In [113]:
 matrix_vector_multipication(U,d)

14.0
5.0
5.0


array([14.,  5.,  5.])

In [118]:
def matrix_matrix_multipication(U,V):
    assert U.shape[1] == V.shape[0]         # CHECKING DIMENSION
    number_of_rows = U.shape[0]
    number_of_columns =V.shape[1]
    
    result = np.zeros((number_of_rows,number_of_columns ))
    for i in range(number_of_columns):
        Vi = V [:, i]
        Uvi =  matrix_vector_multipication(U, Vi)
        result [:, i ]=  Uvi
    return result

In [119]:
 matrix_matrix_multipication(U,V)

14.0
5.0
5.0
20.0
6.0
8.5
13.0
5.0
9.0


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [120]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])