In [39]:
# Creating an array with zeros and ones, or any other particular number with a particular length np.zeros, ones, array []
# Use a particular list of numbers as an array (Full)
# Access and modify an element in an array []
# Range using arange from starting to end points or from zero to end point (not included), or decided breaks using linspace
# Indexing start from zero
# Multidimension arrays
# : mean all
# Random initlization
# element wise operation ** power
# a+ b add two arrays
# diviison by constant or multiply or add
# Comparing arrays element wise
# Filtering based on criteria
# Summerization operation





In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
# Creating Numpy


In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
# List to array
a = np.array([1, 2, 3, 4, 5])
a


array([1, 2, 3, 4, 5])

In [11]:
a [2] = 10
a

array([ 1,  2, 10,  4,  5])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
# Multidimensioal arrays

In [16]:
np.zeros((5, 2)) # rows and columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],   # Array of lists
    [4, 5, 6],
    [8, 9, 10]
]
)

In [18]:
n [0, 1] = 30     # first row second column
n

array([[ 1, 30,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [19]:
n[:, 2] = [1, 1, 1]  # allow rows third column 

In [20]:
n

array([[ 1, 30,  1],
       [ 4,  5,  1],
       [ 8,  9,  1]])

In [ ]:
# Random Initlization

In [26]:
np.random.seed(2)
np.random.rand(5,2) # 5 rows 2 columns, uniform distribution between 0 and 1

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.randn(5, 2) # normal distribution

array([[-2.69056960e-01,  2.23136679e+00],
       [-2.43476758e+00,  1.12726505e-01],
       [ 3.70444537e-01,  1.35963386e+00],
       [ 5.01857207e-01, -8.44213704e-01],
       [ 9.76147160e-06,  5.42352572e-01]])

In [30]:
np.random.seed(2)
100 * np.random.rand(5,2) # 5 rows 2 columns, uniform distribution between 0 and 1

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [35]:
np.random.randint(low= 0 , high = 100, size = (5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

In [37]:
#elment wise
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a * 2

array([0, 2, 4, 6, 8])

In [47]:
b = ((2 * a) + 10) **2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [45]:
a+ b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [ ]:
# Comparison

In [48]:
a >=2

array([False, False,  True,  True,  True])

In [49]:
a >= b

array([False, False,  True,  True,  True])

In [50]:
a [a>=b]

array([2, 3, 4])

In [ ]:
# Summerization

In [53]:
a.sum()
a.mean()

np.float64(2.0)

In [54]:
a.std()

np.float64(1.4142135623730951)

In [55]:
a.min()

np.int64(0)

In [56]:
a.max()

np.int64(4)